### ISSUE TITLE
Chat.py fails (openai + pinecone)

### ISSUE THREAD

**Issue by friofry** [Storia-AI/repo2vec#15]
When running 

```
python src/index.py $GITHUB_REPO_NAME --embedder_type=openai --vector_store_type=pinecone --index_name=$PINECONE_INDEX_NAME

python src/chat.py $GITHUB_REPO_NAME --llm_provider=openai --vector_store_type=pinecone --index_name=$PINECONE_INDEX_NAME
```
I got this error:

```
Traceback (most recent call last):
  File "repo2vec/src/chat.py", line 97, in <module>
    rag_chain = build_rag_chain(args)
                ^^^^^^^^^^^^^^^^^^^^^
  File "repo2vec/src/chat.py", line 26, in build_rag_chain
    retriever = vector_store.build_from_args(args).to_langchain().as_retriever()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo2vec/src/vector_store.py", line 64, in to_langchain
    return Pinecone.from_existing_index(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Pinecone' has no attribute 'from_existing_index'
```

**Comment by iuliaturc** [comment]
Thanks for flagging this @friofry!
I had broken this in my last PR... I guess it's time for unit tests? 😭
